#ifndef POKEHEARTGOLD_CONSTANTS_OPTIONS_H
#define POKEHEARTGOLD_CONSTANTS_OPTIONS_H

enum OptionsTextSpeed {
    OPTIONS_TEXT_SPEED_SLOW = 0,
    OPTIONS_TEXT_SPEED_NORMAL,
    OPTIONS_TEXT_SPEED_FAST
};

#endif // POKEHEARTGOLD_CONSTANTS_OPTIONS_H